### ISSUE TITLE
Crash when start View sometimes

### ISSUE THREAD

**Issue by BilalReffas** [CardinalNow/iOS-CircleProgressView#10]
Code ->  progressPath.addArcWithCenter(center, radius:radius, startAngle:startAngle, endAngle:endAngle, clockwise:!clockwise)

OutPut -> error in __connection_block_invoke_2: Connection interrupted
Assertion failed: (start_angle >= end_angle), function void CG::Path::Subpath::add_arc(const CGPoint &, double, double, double, bool, const CGAffineTransform *), file Paths/path-subpath-arc.cc, line 53.

**Comment by xrolfex** [comment]
Still unable to reproduce.

**Comment by BilalReffas** [comment]
So thanks the problem solve by your update !
