### ISSUE TITLE
can you provide objective-c version??

### ISSUE THREAD

**Issue by cloudjanak** [CardinalNow/iOS-CircleProgressView#11]

**Comment by xrolfex** [comment]
I added the @objc directive to the class, you should be able to pull the swift class into your project and use it in your obj-c project. If needed I could port it over to objc pretty quickly.

**Comment by cloudjanak** [comment]
no i need objective-c without pods

**Comment by xrolfex** [comment]
I will add it to my list, I may have a chance to get to it tonight but it may be tomorrow.

**Comment by xrolfex** [comment]
An Obj-C version has been added to the ProgressView folder. It is not setup with cocopods but you can manually add the source. You are welcome to create another pod spec and submit a pull request. The current development will remain in swift. Thanks.

**Comment by cloudjanak** [comment]
we need objective-c demo project.

**Comment by malcolmhall** [comment]
the problem with swift is the runtime adds 30MB of bloat to your app, so thats why a objc version of the progress bar is best at the moment! thanks.
