### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by nassifbasheer** [CardinalNow/iOS-CircleProgressView#12]
Hi,

I am unable to run the project . It is crashing as it is launched :(
![screen shot 2015-04-18 at 10 55 14 pm](https://cloud.githubusercontent.com/assets/5028245/7216457/40263c68-e61e-11e4-8fcf-f19339acbf6d.png)

**Comment by xrolfex** [comment]
Fixed the issue, it was a missing module name in IB for the progress view. It was a by product of testing the Obj-C version.
