### ISSUE TITLE
Obj C version not found

### ISSUE THREAD

**Issue by paulantony87** [CardinalNow/iOS-CircleProgressView#14]
Could you mention the steps to get the Obj C version.- not the obj C directive -referring to closed issue
Also would you improve on this and add multiple sliders to the same.( each slider will show a different color on different portion of screen)

**Comment by xrolfex** [comment]
@paulantony87 The objc versions of the classes are under the same ProgressView folder. There is not a pod spec for the objc version. As for the enhancement, I'm not quite sure what your referring to. Do you have an example image?

**Comment by paulantony87** [comment]
Hi Eric,

Thanks for reaching out. As for the engancement i was referring to a
progress bar controlled by sliders.  You can take a look the zillow
mortgage app payment calculator for an idea.

But i have figured ot out using pie chart.

Thank you once again

Paul Antony

**Comment by xrolfex** [comment]
I will take a look and see about doing something similar.

**Comment by paulantony87** [comment]
Thank you. I appreciate it.
