### ISSUE TITLE
Unknown class

### ISSUE THREAD

**Issue by peterdruska** [CardinalNow/iOS-CircleProgressView#15]
Hi,

whan I want to assign properties to CircleProgressView class instance, Xcode tells me this: "Unknown class CircleProgressView in Interface Builder file."

I am assigning it in cell like this:

    cell.circleProgressView.progress = 0.64

In cell class I have this connected with storyboard:

    @IBOutlet weak var circleProgressView: CircleProgressView!

I have no solition yet, nothing works for me. Thank you.

**Comment by xrolfex** [comment]
It has to do with the module name that is in the project, double check in IB that you have a module name under the class type field in the inspector window.
