### ISSUE TITLE
can you set a image that fills the center of the circular view? 

### ISSUE THREAD

**Issue by carlosandresSanchez** [CardinalNow/iOS-CircleProgressView#16]

**Comment by xrolfex** [comment]
You can just set an image above the circle progress. Currently it only supports a color. It would be possible to add that support.

**Comment by carlosandresSanchez** [comment]
Yes, thanks!!!

**Comment by carlosandresSanchez** [comment]
Do you think we can implement the class for ```UIImageView```?  In general for all types of UIViews?

**Comment by xrolfex** [comment]
I just posted an updated version that allows you to set a UIImage for the center view that is clipped to the circle path. I updated both the swift and objc versions.
