### ISSUE TITLE
How can animate ?

### ISSUE THREAD

**Issue by priore** [CardinalNow/iOS-CircleProgressView#18]
how can animate automatically with UIView:animateWithDuration:animations: ?
the example below is not working :

```objective-c
    [UIView animateWithDuration:5.0 animations:^{
        self.progressView.progress = 1.0;
    }];
```

**Comment by dehlen** [comment]
I am also very interested in this one. Will have a look by myself in a couple of days when I get some time.

**Comment by jwkelso** [comment]
Hi priore and dehlen:

This is on our list to implement. Please feel free to pull request the behavior if you get something done before we do.

Thanks!

**Comment by xrolfex** [comment]
@dehlen & @priore I have pushed out an updated version that contains a new method/function that can be used to update progress with animation.
```Swift
func setProgress(newProgress: Double, animated: Bool) {}
```
or 
```objective-c
- (void)setProgress:(double)progress animated:(bool)animated;
```

The cocoapods has been updated to version 1.0.7
