### ISSUE TITLE
Progress is not updating instantly

### ISSUE THREAD

**Issue by ghost** [CardinalNow/iOS-CircleProgressView#19]
I am implementing circleProgressView in swift but I can't update progress instantly.

Could you please assist here?

**Comment by jwkelso** [comment]
Hi jimAnderson007,

Can you please provide an example of your issue? I'm afraid I'm having some trouble figuring out what you're experiencing.

Thanks!

**Comment by xrolfex** [comment]
@jimAnderson007 Please ensure that you are updating progress on the main thread.

**Comment by batgun** [comment]
I agree with the jim
Even with code below, its nor updating smoothly:
        dispatch_async(dispatch_get_main_queue()) {
            self.circleProgressView.setProgress(self.barPercent,animated: true)
        }

Can you please help

**Comment by HiveHicks** [comment]
I'm experiencing the same behaviour. Sometimes it takes several seconds for indicator to animate progress, sometimes it happens almost instantly.

**Comment by xrolfex** [comment]
Im taking a look at may be due to the CADisplayLink needing to fire on the next runloop execution. Looking for an alternative.

**Comment by tiagomnh** [comment]
I'm experiencing this issue too. Has anyone figured out a fix?

**Comment by xrolfex** [comment]
Fixed with PR 29.

**Comment by xrolfex** [comment]
Updated with new pod version 1.0.10
