### ISSUE TITLE
Round corner

### ISSUE THREAD

**Issue by BilalReffas** [CardinalNow/iOS-CircleProgressView#20]
Is it possible to draw a round corner for the circle ?

**Comment by jwkelso** [comment]
Hi BilalReffas:

I'm afraid I'm not clear on what you're asking here. Can you please provide an example?

**Comment by xrolfex** [comment]
@BilalReffas Any further information on your request?

**Comment by fabb** [comment]
I think he means a round line cap.

**Comment by xrolfex** [comment]
The current implementation does not support this feature. Feel free to make modification and submit a pull request.
