### ISSUE TITLE
unknown class xcode 7.2

### ISSUE THREAD

**Issue by shixuanteng** [CardinalNow/iOS-CircleProgressView#23]
Xcode giving unknown class error see attached screenshot:

<img width="873" alt="screen shot 2015-12-29 at 11 59 08 pm" src="https://cloud.githubusercontent.com/assets/5069173/12037269/449586cc-ae88-11e5-8d4d-c833a0787ffb.png">

**Comment by xrolfex** [comment]
@shixuanteng Can you provide any more details? The screenshot you attached does not appear to show any error and I have not seen any errors in Xcode 7.2 at this point.

**Comment by shixuanteng** [comment]
@xrolfex here's the error code i'm receiving... did i do anything wrong?

<img width="882" alt="screen shot 2016-01-01 at 7 39 17 pm" src="https://cloud.githubusercontent.com/assets/5069173/12070690/7eb2da2e-b0bf-11e5-9fef-9990bc37809e.png">

**Comment by xrolfex** [comment]
This is most likely cases by a propert in the user run time attributes in inspector. If you clear those and reset your defult styling in interface builder it should go away.

**Comment by shixuanteng** [comment]
@xrolfex hi, tried to create another project, but still having the unknown class error, which is causing the progress not to be loaded

**Comment by xrolfex** [comment]
I have not been able to recreate this issue.
