### ISSUE TITLE
UIImage Aspect Fit/Fill

### ISSUE THREAD

**Issue by sungjp** [CardinalNow/iOS-CircleProgressView#24]
Is there a way to set the content mode of the progress view? I've tried setting it directly, but nothing's working.

**Comment by xrolfex** [comment]
No, at this time only the UIImage itself is exposed as it is drawn via CoreGraphics directly into the context. A PR with a new UIImageView itself would need to be added or additional code in core graphics to handle the different content modes such as listed in this SO: http://stackoverflow.com/questions/8865814/is-it-possible-to-display-an-image-in-core-graphics-with-an-aspect-fit-resize
