### ISSUE TITLE
iOS 7 compatible?

### ISSUE THREAD

**Issue by huynguyencong** [CardinalNow/iOS-CircleProgressView#26]
In Readme file, it is compatible with iOS 7. But in podspec file, it require iOS 8. So, I can't use CocoaPod to install lib. I have to drop file manual. It is compatible iOS 7. Can you edit the podspec file for iOS 7?

**Comment by lavoy** [comment]
:+1:

**Comment by xrolfex** [comment]
Cocoa pods swift support builds as dynamic frameworks. These are only supported in iOS 8+. If you would like to use this in your project, please pull it in manually. See Cocoapods issue on the topic that was marked as resolved. https://github.com/CocoaPods/swift/issues/22
