### ISSUE TITLE
Swift_3_0 branch doesn't build on Xcode8 GM

### ISSUE THREAD

**Issue by skydivedan** [CardinalNow/iOS-CircleProgressView#34]
I tried to build the Swift 3 branch in Xcode8 GM, and got this.

<img width="263" alt="screen shot 2016-09-08 at 11 11 39 am" src="https://cloud.githubusercontent.com/assets/217969/18354834/0f57aba8-75b5-11e6-80b8-47297a6fcc69.png">

**Comment by xrolfex** [comment]
The swift 3 branch will be removed upon release of Xcode 8 today. The repo will be updated for swift 3 as well at that time.
