### ISSUE TITLE
Use as a countdown timer

### ISSUE THREAD

**Issue by otymartin** [CardinalNow/iOS-CircleProgressView#46]
@xrolfex 
Can this be used as an animated countdown timer?
I cant seem to make it run that way?

Thanks

**Comment by markogley** [comment]
Yes it is possible. I have done this for a test app I was writing. This some code that I wrote in Swift 3 to do this.

     func updateTimer() {
        //this is a countdown time, reverse logic for count up timer
        if updatedCounter > 0 {
            updatedCounter = updatedCounter - 1
        //formats the counter to show minutes and seconds
            let minsCounter = (updatedCounter / 60) % 60
            let secondsCounter = updatedCounter % 60
            timerLabel.text = String(format: "%02i:%02i", minsCounter,secondsCounter)
            //global variable to check if the user is working out or resting for my app
            if workout {
         //calls updateProgressview to update the Circle Progress View
            updateProgressView(updatedCounter: updatedCounter, originalCounter: workoutCounter!)
            }
            if !workout {
                updateProgressView(updatedCounter: updatedCounter, originalCounter: restCounter!)
            }
        } else {
          //resets the progress shown by the timer
            circleProgressView.setProgress(newProgress: 100.0, animated: false)
        //kills the timer so it can be reset
            timer.invalidate()
        //changes global variable to opposite state
            workout = !workout
        //calls setup counter to reset timer parameters
            setUpCounter()
        }
    }

    //method called to show the changes to the circle progress view
    func updateProgressView(updatedCounter: Int, originalCounter: Int) {
            let decimalProgress : Double = ((Double(updatedCounter) / Double(originalCounter)) * 100.0) / 100.0
            circleProgressView.progress = Double(decimalProgress)
         }

    func setUpCounter() {
            //checks to see if user is working out 
            if workout {
               //makes sure optional exists
                if let unwrappedCounter = workoutCounter {
                    //updates the time used in the counter
                    updatedCounter = unwrappedCounter
                    //fixes timer label to show total, because in update timer function it begin subtracting by 1 so total nevershowed.
                    timerLabel.text = String(format: "00:%02i", updatedCounter)
                    //get exercise data
                    accessData()
                }
            
            }else if !workout {
                //check to make sure new time for timer exists
                if let unwrappedCounter = restCounter {
                    //reset the time used by the counter
                    updatedCounter = unwrappedCounter
                    //same as note above
                    timerLabel.text = String(format: "00:%02i", updatedCounter)
                }
            }
            #tells the timer to restart by call this method
            fireTimer()   
        }

    
    func fireTimer() {
            #Swift 3 timer function used to start timer and calls selector of update timer that countdown and calls update to progress view.
        timer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true)
    }


I hope this helps. Feel free to ask any questions.
