### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BilalReffas** [CardinalNow/iOS-CircleProgressView#5]
Assertion failed: (start_angle >= end_angle), function void CG::Path::Subpath::add_arc(const CGPoint &, double, double, double, bool, const CGAffineTransform *), file Paths/path-subpath-arc.cc, line 53.

**Comment by BilalReffas** [comment]
Crash when start MultitaskingView and go back to the app...

**Comment by xrolfex** [comment]
Are you able to provide any additional insight? I am currently unable to reproduce the issue.

**Comment by BilalReffas** [comment]
No sorry that's all :( But it's strange .. only sometimes it's crashes

**Comment by xrolfex** [comment]
Are you filling the progress clockwise or emptying the progress counter clockwise?

**Comment by BilalReffas** [comment]
I'm filling the progress in default clockwise yes

**Comment by xrolfex** [comment]
Can you post any of the code you are using to change the progress or instantiate the progress view?

**Comment by BilalReffas** [comment]
progressView.backgroundColor = UIColor.clearColor()
        progressView.trackFillColor = UIColor(red: 0.0, green: 122.0/255.0, blue: 1.0, alpha: 1.0)
        progressView.centerFillColor = UIColor(red: 255.0, green: 255.0, blue: 255.0, alpha: 1.0)
        progressView.trackWidth = 9.0
        progressView.progress = self.proErg

**Comment by xrolfex** [comment]
I have not been able to reproduce this issue. My only guess is that your self.proErg value is a negative value or a progress value that is not between 0 and 1.

**Comment by BilalReffas** [comment]
The value It's between 0 and 1. But sometimes when my View load new than the progress changes.

**Comment by xrolfex** [comment]
With out seeing the project, I'm having a hard time reproducing the issue.
