### ISSUE TITLE
Create new Podspec version

### ISSUE THREAD

**Issue by honkmaster** [CardinalNow/iOS-CircleProgressView#58]
Hi, 

your last commit resolved the 

> 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

issue. Please create a new Podspec version to make it accessible.

Thanks

**Comment by jwolkovitzs** [comment]
also having issue getting the latest version of the pod when running pod update

**Comment by colinhumber** [comment]
Same here.

**Comment by xrolfex** [comment]
Will be fixed in next release.
