### ISSUE TITLE
Build error when trying migrate to Swift 4

### ISSUE THREAD

**Issue by felipelmota** [CardinalNow/iOS-CircleProgressView#62]
Argument of '#selector' refers to instance method 'displayLinkTick()' that is not exposed to Objective-C

Class affected: CircleProgressView.

**Comment by valeriologiudice** [comment]
Any chance to have the library updated and functional for Xcode 9 and Swift 4? This is a good library and deserves to be updated. Best.

**Comment by xrolfex** [comment]
Will be fixed in next build.
