### ISSUE TITLE
I want to add two labels inside circle, where can I add

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [CardinalNow/iOS-CircleProgressView#65]
Thanks for the good library,But, I want to add two labels inside circle, how can I add, and I want to show some animation while loading the circle, we are not using swift button to increase value, I have some Integer value, while loading that value I want to show some kind animation like loading circle.

Can you suggest me, how to go this?

**Comment by xrolfex** [comment]
For the two labels you can add them as subviews to the "contentView", that is the center view. As for the animation while loading that is entirely up to you. You could simply use a UIActivityIndicator in the content view to show the center as a loading indicator of some sort.

**Comment by AnilkumarRabhasa** [comment]
Thanks for the reply, I already did it.
