### ISSUE TITLE
Updating screen value causing error

### ISSUE THREAD

**Issue by felipelmota** [CardinalNow/iOS-CircleProgressView#68]
During runtime usage, CircleProgressView (progress value) must be used from main thread.

![screen shot 2018-01-09 at 09 33 58](https://user-images.githubusercontent.com/3216187/34721148-650a4844-f520-11e7-880b-5190443e3cb6.png)

**Comment by farshadmb** [comment]
@felipelmota because you set progress value on non-main thread queue.

**Comment by xrolfex** [comment]
@farshadmb Is correct, you should only update the progress on the main thread. You can use a dispatch_async with the main queue to update this value.
