### ISSUE TITLE
Track Background Color applied to center when Center Fill Color is clear

### ISSUE THREAD

**Issue by jagge1988** [CardinalNow/iOS-CircleProgressView#69]
Hi, 

I was playing a little bit around with your nice view when I recognised a small issue. 
I expected when I set the `Center Fill Color` to clear and the `Track Background Color` to something that the center will still be the clear. Instead it has the `Track Background Color`

How to reproduce: 
1. add CircleProgressView to an view with the Xcode interface builder
2. in the Attributes Inspector change `Track Background Color` to black
3. change `Center Fill Color` to clear

expected outcome: center is clear (usually white through white background)

actual outcome: center is black

**Comment by xrolfex** [comment]
This was initially designed with this to reduce the number of draws. I would certainly entertain the idea of doing an even odd draw but I have not implemented it as i could just set the center color the same as the background if i wanted a donut shape.
