### ISSUE TITLE
Incorrect value for source_files in podspec

### ISSUE THREAD

**Issue by nicolaschengdev** [CardinalNow/iOS-CircleProgressView#7]
Hi CardinalNow,

thank you very much for your work.

In your podspec you write:
```
s.source_files = 'CircleProgressView/*'
```
This value should be `ProgressView/*`.

Because source file *CircleProgressView.swift* is in **ProgressView** folder.
And **CircleProgressView** folder only contains the demo.

**Comment by xrolfex** [comment]
Thanks for the info. The pod spec has been changed updated and submitted. You can now point to pod version 1.0.1
