### ISSUE TITLE
Request - bump pod version

### ISSUE THREAD

**Issue by yuweipei** [CardinalNow/iOS-CircleProgressView#73]
Hi there, thanks for the nice pod and can't say enough thanks to you guys. 
I've converted my app to swift 4.2 and compiler is complaining on CircleProgressView. It seems that the latest swift 4.2 was made to master yet pushed to pods. can you do a version bump and `pod repo push`?
Thanks

**Comment by dvluong** [comment]
Running into this issue as well.

**Comment by gblock92** [comment]
Me too

**Comment by erikvillegas** [comment]
Same

**Comment by jspitzig** [comment]
Version 1.2.0 has been pushed and includes the changes for Swift 4.2.
