### ISSUE TITLE
CocoaPods 0.36.0 - CircleProgressView in a Swift project

### ISSUE THREAD

**Issue by Progeny** [CardinalNow/iOS-CircleProgressView#8]
Hello, if you want to use CircleProgressView in a Swift project, it has to be compiled as a Framework, that whats cocoapod does, but the source needs to be modified.

Class's access must be public, otherwise I cannot declare a object of class CircleProgressView
Some vars needs to be public too, like the "progress" var.

Please address this issue, because I don't want to fix it manually every time I do "pod install" to update my project ;-)

@IBDesignable public class CircleProgressView: UIView {
    @IBInspectable public var progress: Double = 0.000001 {
        didSet { setNeedsDisplay() }
    }

**Comment by xrolfex** [comment]
If you would like to submit a pull request, I will merge it in.

**Comment by xrolfex** [comment]
Merged Pull request. Closed.

**Comment by BilalReffas** [comment]
is it possible to animate the circle ?

**Comment by xrolfex** [comment]
It would be possible with changing how the drawing is done to use a CAShapeLayer.
